FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN apk add --no-cache git
RUN go mod download
COPY kafka-example/producer/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o producer .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/producer/ .
CMD ["./producer"]
